GovernorPortal.UI/Areas/SecurityGuard/Models/GrantRolesToUserViewModel.cs
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Security;

namespace SecurityGuard.ViewModels
{
    public class GrantRolesToUserViewModel
    {
        public MembershipUser User { get; set; }
        public string UserName { get; set; }
        public SelectList AvailableRoles { get; set; }
        public SelectList GrantedRoles { get; set; }
    }
}

GovernorPortal.UI/Areas/SecurityGuard/Controllers/MembershipController.cs
using System;
using System.Web.Mvc;
using System.Web.Security;
using SecurityGuard.Core.Extensions;
using SecurityGuard.Services;
using SecurityGuard.Core.Attributes;
using routeHelpers = SecurityGuard.Core.RouteHelpers;
using SecurityGuard.Interfaces;
using SecurityGuard.ViewModels;
using GovernorPortal.UI.Controllers;

namespace GovernorPortal.UI.Areas.SecurityGuard.Controllers
{
    [Authorize(Roles = "SecurityGuard")]
    public partial class MembershipController : BaseController
    {

        #region ctors

        private IMembershipService membershipService;
        private readonly IRoleService roleService;

        public MembershipController()
        {
            this.roleService = new RoleService(Roles.Provider);
            this.membershipService = new MembershipService(Membership.Provider);
        }

        #endregion

        #region Index Method
        public virtual ActionResult Index(string filterby, string searchterm)
        {
            ManageUsersViewModel viewModel = new ManageUsersViewModel();
            viewModel.Users = null;
            viewModel.FilterBy = filterby;
            viewModel.SearchTerm = searchterm;

            int totalRecords;
            int page = Convert.ToInt32(Request["page"]);
            int pageSize = Convert.ToInt32(Request["pagesize"]);
            if (pageSize == 0)
                pageSize = 25;

            viewModel.PageSize = pageSize;

            if (!string.IsNullOrEmpty(filterby))
            {
                if (filterby == "all")
                {
                    viewModel.PaginatedUserList = membershipService.GetAllUsers(page, pageSize, out totalRecords).ToPaginatedList(page, pageSize, totalRecords, searchterm, filterby);
                }
                else if (!string.IsNullOrEmpty(searchterm))
                {
                    string query = searchterm + "%";
                    if (filterby == "email")
                    {
                        viewModel.PaginatedUserList = membershipService.FindUsersByEmail(query, page, pageSize, out totalRecords).ToPaginatedList(page, pageSize, totalRecords, searchterm, filterby);
                    }
                    else if (filterby == "username")
                    {
                        viewModel.PaginatedUserList = membershipService.FindUsersByName(query, page, pageSize, out totalRecords).ToPaginatedList(page, pageSize, totalRecords, searchterm, filterby);
                    }
                }
            }

            return View(viewModel);
        }
        #endregion

        #region Create User Methods

        public virtual ActionResult CreateUser()
        {
            var model = new RegisterViewModel()
            {
                RequireSecretQuestionAndAnswer = membershipService.RequiresQuestionAndAnswer
            };
            return View(model);
        }

        /// <summary>
        /// This method redirects to the GrantRolesToUser method.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public virtual ActionResult CreateUser(RegisterViewModel model)
        {
            MembershipUser user;
            MembershipCreateStatus status;
            user = membershipService.CreateUser(model.UserName, model.Password, model.Email, model.SecretQuestion, model.SecretAnswer, model.Approve, out status);

            return routeHelpers.Actions.GrantRolesToUser(user.UserName);
        }

        /// <summary>
        /// An Ajax method to check if a username is unique.
        /// </summary>
        /// <param name="userName"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult CheckForUniqueUser(string userName)
        {
            MembershipUser user = membershipService.GetUser(userName);
            JsonResponse response = new JsonResponse();
            response.Exists = (user == null) ? false : true;

            return Json(response, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Delete User Methods

        [HttpPost]
        [MultiButtonFormSubmit(ActionName = "UpdateDeleteCancel", SubmitButton = "DeleteUser")]
        public ActionResult DeleteUser(string UserName)
        {
            if (string.IsNullOrEmpty(UserName))
            {
                throw new ArgumentNullException("userName");
            }

            try
            {
                membershipService.DeleteUser(UserName);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "There was an error deleting this user. - " + ex.Message;
            }

            return RedirectToAction("Update", new { userName = UserName });
        }



        #endregion

        #region Update User Details Methods

        [HttpGet]
        public ActionResult Update(string userName)
        {
            MembershipUser user = membershipService.GetUser(userName);
            
            UserViewModel viewModel = new UserViewModel();
            viewModel.User = user;
            viewModel.RequiresSecretQuestionAndAnswer = membershipService.RequiresQuestionAndAnswer;
            viewModel.Roles = roleService.GetRolesForUser(userName);

            return View(viewModel);
        }

        [HttpPost]
        [MultiButtonFormSubmit(ActionName = "UpdateDeleteCancel", SubmitButton = "UpdateUser")]
        public ActionResult UpdateUser(string UserName)
        {
            if (string.IsNullOrEmpty(UserName))
            {
                throw new ArgumentNullException("userName");
            }

            MembershipUser user = membershipService.GetUser(UserName);

            try
            {
                user.Comment = Request["User.Comment"];
                user.Email = Request["User.Email"];

                membershipService.UpdateUser(user);
                TempData["SuccessMessage"] = "The user was updated successfully!";

            }
            catch (Exception)
            {
                TempData["ErrorMessage"] = "There was an error updating this user.";
            }

            return RedirectToAction("Update", new { userName = user.UserName });
        }


        #region Ajax methods for Updating the user

        [HttpPost]
        public ActionResult Unlock(string userName)
        {
            JsonResponse response = new JsonResponse();

            MembershipUser user = membershipService.GetUser(userName);

            try
            {
                user.UnlockUser();
                response.Success = true;
                response.Message = "User unlocked successfully!";
                response.Locked = false;
                response.LockedStatus = (response.Locked) ? "Locked" : "Unlocked";
            }
            catch (Exception)
            {
                response.Success = false;
                response.Message = "User unlocked failed.";
            }

            return Json(response);
        }

        [HttpPost]
        public ActionResult ApproveDeny(string userName)
        {
            JsonResponse response = new JsonResponse();

            MembershipUser user = membershipService.GetUser(userName);

            try
            {
                user.IsApproved = !user.IsApproved;
                membershipService.UpdateUser(user);

                string approvedMsg = (user.IsApproved) ? "Approved" : "Denied";

                if (user.IsApproved)
                {
                    // Send a confirmation email to tell the user they're approved

                }

                response.Success = true;
                response.Message = "User " + approvedMsg + " successfully!";
                response.Approved = user.IsApproved;
                response.ApprovedStatus = (user.IsApproved) ? "Approved" : "Not approved";
            }
            catch (Exception)
            {
                response.Success = false;
                response.Message = "User unlocked failed.";
            }

            return Json(response);
        }

        #endregion

        #endregion

        #region Cancel User Methods

        [HttpPost]
        [MultiButtonFormSubmit(ActionName = "UpdateDeleteCancel", SubmitButton = "UserCancel")]
        public ActionResult Cancel()
        {
            return RedirectToAction("Index");
        }

        #endregion

        #region Grant Users with Roles Methods

        /// <summary>
        /// Return two lists:
        ///   1)  a list of Roles not granted to the user
        ///   2)  a list of Roles granted to the user
        /// </summary>
        /// <param name="username"></param>
        /// <returns></returns>
        public virtual ActionResult GrantRolesToUser(string username)
        {
            if (string.IsNullOrEmpty(username))
            {
                return RedirectToAction("Index");
            }

            GrantRolesToUserViewModel model = new GrantRolesToUserViewModel();
            model.UserName = username;
            model.AvailableRoles = (string.IsNullOrEmpty(username) ? new SelectList(roleService.GetAllRoles()) : new SelectList(roleService.AvailableRolesForUser(username)));
            model.GrantedRoles = (string.IsNullOrEmpty(username) ? new SelectList(new string[] { }) : new SelectList(roleService.GetRolesForUser(username)));

            return View(model);
        }

        /// <summary>
        /// Grant the selected roles to the user.
        /// </summary>
        /// <param name="userName"></param>
        /// <param name="roleNames"></param>
        /// <returns></returns>
        [HttpPost]

GovernorPortal.UI/Areas/SecurityGuard/Views/Membership/CreateUser.cshtml
@model SecurityGuard.ViewModels.RegisterViewModel

@{
    ViewBag.Title = "CreateUser";
}

<div id="breadcrumb">
    @Html.ActionLink("Dashboard", "Index", "Dashboard") > 
    @Html.ActionLink("Manage Users", "Index", "Membership") > 
    Create User
</div>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<h2>Create User</h2>

<ul>
    <li>To be a minimum of @Membership.MinRequiredPasswordLength characters in length.</li>
    @if (Membership.MinRequiredNonAlphanumericCharacters > 0)
    {
        <li>To have a minimum of @Membership.MinRequiredNonAlphanumericCharacters non-alpha numeric characters included, such as &quot;<span style="font-family: Courier New; font-size: 16px;">(){}-_*&^%$#@@!</span>&quot;.</li>
    }
</ul>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Enter User Credentials</legend>

        <div class="row">
            <label>@Html.LabelFor(model => model.UserName)</label>
            <div class="inputs">
                <span class="input_wrapper">@Html.TextBoxFor(model => model.UserName, new { @class = "text" })</span>
                <span class="system negative" id="username-message">@Html.ValidationMessageFor(model => model.UserName)</span>
            </div>
        </div>

        <div class="row">
            <label>@Html.LabelFor(model => model.Email)</label>
            <div class="inputs">
                <span class="input_wrapper">@Html.TextBoxFor(model => model.Email, new { @class = "text" })</span>
                <span class="system negative">@Html.ValidationMessageFor(model => model.Email)</span>
            </div>
        </div>

        <div class="row">
            <label>@Html.LabelFor(model => model.Password)</label>
            <div class="inputs">
                <span class="input_wrapper">@Html.PasswordFor(model => model.Password, new { @class = "text" })</span>
                <span class="system negative">@Html.ValidationMessageFor(model => model.Password)</span>
            </div>
        </div>

        <div class="row">
            <label>@Html.LabelFor(model => model.ConfirmPassword)</label>
            <div class="inputs">
                <span class="input_wrapper">@Html.PasswordFor(model => model.ConfirmPassword, new { @class = "text" })</span>
                <span class="system negative">@Html.ValidationMessageFor(model => model.ConfirmPassword)</span>
            </div>
        </div>

        @if (Model.RequireSecretQuestionAndAnswer)
        {
        <div class="row">
            <label>@Html.LabelFor(model => model.SecretQuestion)</label>
            <div class="inputs">
                <span class="input_wrapper">@Html.TextBoxFor(model => model.SecretQuestion, new { @class = "text" })</span>
                <span class="system negative">@Html.ValidationMessageFor(model => model.SecretQuestion)</span>
            </div>
        </div>

        <div class="row">
            <label>@Html.LabelFor(model => model.SecretAnswer)</label>
            <div class="inputs">
                <span class="input_wrapper">@Html.TextBoxFor(model => model.SecretAnswer, new { @class = "text" })</span>
                <span class="system negative">@Html.ValidationMessageFor(model => model.SecretAnswer)</span>
            </div>
        </div>
        }

        <div class="row">
            <label>@Html.LabelFor(model => model.Approve)</label>
            <div class="inputs">
                <span class="input_wrapper">@Html.EditorFor(model => model.Approve, new { @class = "text" })</span>
                <span class="system">@Html.ValidationMessageFor(model => model.Approve)</span>
            </div>
        </div>


        @Html.HiddenFor(model => model.RequireSecretQuestionAndAnswer)
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to Manage Users", "Index")
</div>


<script type="text/javascript">

    $(function () {

        var msg = $("#username-message");
        $("#UserName").blur(function () {

            var username = $(this).val();

            if (username.length == 0) {
                alert("No username.");
                return;
            }

            $.ajax({
                url: '@Url.Action("CheckForUniqueUser", "Membership")',
                dataType: 'json',
                type: 'GET',
                data: { userName: username },
                success: OnCheckForUniqueUserSuccess,
                error: OnCheckForUniqueUserError
            });
        });

        function OnCheckForUniqueUserSuccess(data) {
            if (data.Exists) {
                msg.text("This username already exists.  Please enter a new one.");
            }
        }

        function OnCheckForUniqueUserError(xhr, status, error) {
            msg.text("There was an error checking uniqueness.");
        }
    });

</script>

GovernorPortal.UI/Areas/SecurityGuard/Views/Membership/GrantRolesToUser.cshtml
@model SecurityGuard.ViewModels.GrantRolesToUserViewModel
@{
    ViewBag.Title = "GrantRolesToUser";
}

<div id="breadcrumb">
    @Html.ActionLink("Dashboard", "Index", "Dashboard") > 
    @Html.ActionLink("Manage Users", "Index", "Membership") > 
    Grant Roles To User
</div>

<h2>
    Grant Roles To User</h2>
<p>
    Clicking the &quot;Grant&quot; or &quot;Revoke&quot; buttons will execute that command.</p>
<p>
    Grant any of the following roles to: <span id="username-to-grant-roles">@Model.UserName</span></p>

<ul class="system_messages" style="display: none;">
    <li><span class="ico"></span><strong class="system_title"></strong></li>
</ul>

<fieldset style="float: left; height: 300px;">
    <div id="available-roles">
        <h3>
            Available roles</h3>
        @Html.ListBox("AvailableRoles", Model.AvailableRoles)
    </div>
    <div id="grant-controls">
        <button id="grant-button">
            Grant --&gt;</button><br />
        <button id="revoke-button">
            &lt;-- Revoke</button>
    </div>
    <div id="granted-roles">
        <h3>
            Granted Roles</h3>
        @Html.ListBox("GrantedRoles", Model.GrantedRoles)
    </div>
</fieldset>
<div style="clear:both;"></div>

<script type="text/javascript">
    $(function () {

        var message = $(".system_messages");

        /******************************************************
        * Begin Grant/Revoke commands
        ******************************************************/
        var availableList = $("#AvailableRoles");
        var grantedList = $("#GrantedRoles");

        $("#grant-button").click(function () {
            // First check if any items in the available list
            // are selected.
            if (availableList.val() == null) {
                alert("You must select a role to grant.");
                return;
            }

            // Then move the selected list items to the 
            // granted roles list.
            move_list_items("AvailableRoles", "GrantedRoles");

            // Now take all the roles from the granted list
            // and create a single comma-delimited list.
            var grantedRoles = "";
            $.each(grantedList.val(), function (index, data) {
                grantedRoles += data + ",";
            });

            // Now execute the command using jQuery ajax.
            $.ajax({
                url: '@Url.Action("GrantRolesToUser", "Membership")',
                dataType: 'json',
                type: 'POST',
                data: { userName: '@Model.UserName', roles: grantedRoles },
                success: OnGrantedSuccess,
                error: OnGrantedError
            });
        });

        function OnGrantedSuccess(data) {
            message.show().delay(5000).fadeOut();    // Show the message
            $("li", message).addClass("green");      // Apply the Green style
            $("strong", message).text(data.Message); // Insert the message
        }

        function OnGrantedError(xhr, status, error) {
            alert(error);
        }



        $("#revoke-button").click(function () {
            // First make sure at least one role in the 
            // granted list is selected to revoke.
            if (grantedList.val() == null) {
                alert("You must select a role to revoke.");
                return;
            }

            // Now move the item back to the Available list.
            move_list_items("GrantedRoles", "AvailableRoles");

            // Now make a comma-delimited string of revoked items.
            var revokedRoles = "";
            $.each(availableList.val(), function (index, data) {
                revokedRoles += data + ",";
            });

            // Now execute the command using jQuery ajax.
            $.ajax({
                url: '@Url.Action("RevokeRolesForUser", "Membership")',
                dataType: 'json',
                type: 'POST',
                data: { userName: '@Model.UserName', roles: revokedRoles },
                success: OnRevokedSuccess,
                error: OnRevokedError
            });
        });

        function OnRevokedSuccess(data) {
            message.show().delay(5000).fadeOut();
            $("li", message).addClass("green");
            $("strong", message).text(data.Message);
        }

        function OnRevokedError(xhr, status, error) {
            alert(error);
        }

        // This function moves items from one list to the other.
        function move_list_items(sourceid, destinationid) {
            $("#" + sourceid + "  option:selected").appendTo("#" + destinationid);
        }
        /******************************************************
        * End Grant/Revoke commands
        ******************************************************/



    });
</script>

GovernorPortal.UI/Areas/SecurityGuard/Views/Membership/Index.cshtml
@model SecurityGuard.ViewModels.ManageUsersViewModel
@{
    ViewBag.Title = "Index";
}
<div id="breadcrumb">
    @Html.ActionLink("Dashboard", "Index", "Dashboard") > Manage Users
</div>
<h2>
    Manage Users</h2>
<p>
    To Grant a user to Roles, click a radio button next to the user name then click
    the &quot;Grant Roles To User&quot; link.</p>
<p>@Html.ActionLink("Create User", "CreateUser", "Membership", new { area = "SecurityGuard" }, null)
    | @Html.ActionLink("Grant Roles to User", "GrantRolesToUser", "Membership", new { area = "SecurityGuard" }, new { id = "grant-roles-to-user", disabled = "disabled" })</p>
@using (Html.BeginForm())
{
    <p><select id="filterby" name="filterby">
        <option value="all" @if(Model.FilterBy == "all"){ <text>selected="selected"</text>}>View All</option>
        <option value="username" @if (Model.FilterBy == "username"){ <text>selected="selected"</text>}>UserName</option>
        <option value="email" @if (Model.FilterBy == "email"){ <text>selected="selected"</text>}>Email</option>
    </select>
    <text>&nbsp;Starts with:</text> @Html.TextBox("searchterm", Model.SearchTerm, null) 

    <input type="submit" id="filter-button" value="Search" /></p>
}
<br />
@if (Model.PaginatedUserList != null)
{
    if (Model.PaginatedUserList.TotalCount == 0)
    {
    <p>No users for this search.</p>
    }
    else
    {
    <text>Records: @Model.PaginatedUserList.TotalCount.ToString()</text>
    <div class="section_inner">
        <div class="table_wrapper">
            <div class="table_wrapper_inner">
                <table cellpadding="0" cellspacing="0" width="100%">
                    <tbody>
                        <tr>
                            <th>
                            </th>
                            <th>
                                UserName
                            </th>
                            <th>
                                Is Approved?
                            </th>
                            <th>
                                Status
                            </th>
                            <th>
                                Email
                            </th>
                            <th>
                                Last Activity
                            </th>
                        </tr>
                        @foreach (MembershipUser item in Model.PaginatedUserList)
                        {
                            <tr>
                                <td>
                                    <input type="radio" name="userName" value="@item.UserName" class="userRadio" />
                                </td>
                                <td>@Html.ActionLink(item.UserName, "Update", "Membership", new { userName = item.UserName }, null)
                                </td>
                                <td>
                                    @if (item.IsApproved)
                                    {
                                        <text><span class="system positive">Approved</span></text>
                                    }
                                    else
                                    {
                                        <text><span class="system negative">Not Approved</span></text>   
                                    }
                                </td>
                                <td>
                                    @if (item.IsLockedOut)
                                    {
                                        <text><span class="system negative">Locked</span></text>
                                    }
                                    else
                                    {
                                        <text><span class="system positive">Unlocked</span></text>
                                    }
                                </td>
                                <td>
                                    @item.Email
                                </td>
                                <td>@string.Format("{0:g}", item.LastActivityDate)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
					<!--[if !IE]>start pagination<![endif]-->
					<div class="pagination">
                    
						<span class="page_no">Page 1 of @Model.PaginatedUserList.TotalPages</span>
						
						<ul class="pag_list">
							<li>
                            @if (Model.PaginatedUserList.HasPreviousPage)
                            {
                                @Html.ActionLink("Previous", "Index", "Membership", new { page = Model.PaginatedUserList.PageIndex - 1, pagesize = Model.PaginatedUserList.PageSize, searchterm = Model.PaginatedUserList.searchterm, filterby = Model.PaginatedUserList.filterby }, null);
                            }
                            else
                            {
                                <text>Previous</text>
                            }
                            </li>

                            @for (int i = 0; i < Model.PaginatedUserList.TotalPages; i++)
                            {
                                if (i == Model.PaginatedUserList.PageIndex){
                                    <li><span>@((i+1).ToString())</span></li>
                                }else{
                                    <li>@Html.ActionLink((i + 1).ToString(), "Index", "Membership", new { page = i, pagesize = Model.PaginatedUserList.PageSize, searchterm = Model.PaginatedUserList.searchterm, filterby = Model.PaginatedUserList.filterby }, null)</li>
                                }
                            }


							<li>...</li>
							<li>@Html.ActionLink(Model.PaginatedUserList.TotalPages.ToString(), "Index", "Membership", new { page = Model.PaginatedUserList.TotalPages - 1, pagesize = Model.PaginatedUserList.PageSize, searchterm = Model.PaginatedUserList.searchterm, filterby = Model.PaginatedUserList.filterby }, null)</li>
							<li>
                            @if (Model.PaginatedUserList.HasNextPage)
                            {
                                @Html.ActionLink("Next", "Index", "Membership", new { page = Model.PaginatedUserList.PageIndex + 1, pagesize = Model.PaginatedUserList.PageSize, searchterm = Model.PaginatedUserList.searchterm, filterby = Model.PaginatedUserList.filterby }, null);
                            }
                            else
	                        {
                                <text>Next</text>
	                        }
                            </li>
						</ul>

                        <div id="page-size">
                        Page Size: <select id="pagesize" name="pagesize">
                        <option value="25" @if(Model.PageSize == 25){<text>selected="selected"</text>}>25</option>
                        <option value="50" @if(Model.PageSize == 50){<text>selected="selected"</text>}>50</option>
                        <option value="100" @if(Model.PageSize == 100){<text>selected="selected"</text>}>100</option>
                        </select>
                        </div>

					</div>
					<!--[if !IE]>end pagination<![endif]-->       
    }
}
<script type="text/javascript">

    $(function () {

        /**************************************************
        * Begin Radio Button functions
        *
        * This captures radio button event clicks and 
        * enables the "Grant Roles To User" link.
        **************************************************/
        var anchor = $("a#grant-roles-to-user");
        //anchor.attr("disabled", "disabled");

        $(".userRadio").click(function () {
            // Get the value of the clicked radio button
            // which is the username.
            var userName = $(this).val();

            // Get a reference to the "href" of the link.
            var href = anchor.attr("href");

            // Concatenate the existing href value with the username
            var newHref = href + "/" + userName;

            // Replace the existing href value with the new one
            anchor.attr("href", newHref);

            // Remove the disabled attribute on the 
            // Grant Roles to User link
            anchor.removeAttr("disabled");
        });

        /**************************************************
        * End Radio Button functions
        **************************************************/



        /**************************************************
        * Begin FilterBy functions
        *
        * This will enable or disable the search field
        * if the "ViewAll" selection is chosen.
        **************************************************/

        $("#filterby").live('change', function () {
            var optionValue = $("option:selected", this).val();
            if (optionValue == "all") {
                // Clear the search field
                $("#searchterm").val("");

                // Disable the search term field
                $("#searchterm").attr("disabled", "disabled");
            } else {
                $("#searchterm").removeAttr("disabled");
            }
        });


        function InitSearchField() {
            var filterbyVal = $("#filterby option:selected").val();
            if (filterbyVal == "all") {
                $("#searchterm").attr("disabled", "disabled");
            }
        }

        InitSearchField();

        /**************************************************
        * End FilterBy functions
        **************************************************/



        /**************************************************
        * Begin PageSize functions
        *
        * This handles the page size selected change functions.
        **************************************************/

        $("#page-size").change(function () {
            var filterbyVal = $("#filterby option:selected").val();
            var searchtermVal = $("#searchterm").val();
            var pageSizeVal = $("option:selected", this).val();

            location.href = '/SecurityGuard/Membership/index/' + filterbyVal + '/' + searchtermVal + '?pagesize=' + pageSizeVal;
        });

        /**************************************************
        * End PageSize functions
        **************************************************/


    });

</script>