GovernorPortal.UI/Controllers/MeetingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GovernorPortal.UI.Models;

namespace GovernorPortal.UI.Controllers
{
    public class MeetingController : Controller
    {
        //
        // GET: /Meeting/
        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.ShowMeetingEdit = true;

            return View();
        }

        [HttpGet]
        public ActionResult Edit()
        {
            string meetingId = Request["MeetingId"];
            // var model = new MeetingModel(int.Parse(meetingId));
            var model = TempToRemove.GetMeeting();

            return View(model);
        }

        [HttpPost]
        public virtual ActionResult Edit(MeetingModel model)
        {
            if (ModelState.IsValid)
            {
            }
            return View();
        }
    }
}

GovernorPortal.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <div id="header">
            <div id="title">
                <h1>@System.Configuration.ConfigurationManager.AppSettings["WebsiteTitle"]</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <div id="menucontainer">
                <ul id="menu">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Meetings", "Index", "Meeting")</li>
                        <li>@Html.ActionLink("Profile", "Index", "Profile")</li>
                        <li>@Html.ActionLink("Change Password", "ChangePassword", "SGAccount")</li>

                        if (User.IsInRole("Administrator"))
                        {
                            <li>@Html.ActionLink("Administration", "Index", "Administration")</li>
                        }
                    }               
                </ul>
            </div>
        </div>
        <div id="main">
            @RenderBody()
        </div>
        <div id="footer">
        </div>
    </div>
</body>
</html>

GovernorPortal.UI/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "SGAccount") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "SGAccount") ]
}

GovernorPortal.UI/Views/Shared/_MeetingsPartial.cshtml
@using System.Collections.ObjectModel
@using GovernorPortal.UI.Models;
@using GovernorPortal.UI;

@{ 
    Collection<MeetingModel> meetings;
    if (ViewBag.ShowAllMeetings == null || ViewBag.ShowAllMeetings) {
    <h3>All meetings:</h3>
        meetings = TempToRemove.GetMeetings();
    } else {
    <h3>Upcoming meetings:</h3>
        meetings = TempToRemove.GetMeetings();
    }

    TermModel currentTerm = TermModel.GetTerm(DateTime.Now);
    var ms = meetings.Where(m => m.Term.Year == currentTerm.Year).OrderBy(m => m.DateTime);
    }

    <table>
    @foreach (MeetingModel m in ms) {
            <tr>
                <td>@m.Title:</td>
                <td>@m.DateTime.Date.ToLongDateString()</td>
             @if (User.IsInRole("Administrator") && (ViewBag.ShowMeetingEdit != null && ViewBag.ShowMeetingEdit))
             {
                <td>@Html.ActionLink("Edit", "Edit", "Meeting", new { MeetingId = m.MeetingId }, null)</td>
             }
            </tr>
         }
             @if (User.IsInRole("Administrator") && (ViewBag.ShowMeetingEdit != null && ViewBag.ShowMeetingEdit))
             {
                <tr><td colspan="3">@Html.ActionLink("Add a new meeting", "Add", "Meeting")</td></tr>
             }
    </table>